### ISSUE TITLE
when calling "Get Profile"

### ISSUE THREAD

**Issue by issofttech2015** [dipinarora9/flutter_truecaller#2]
com.example.flutter_truecaller_example.mainactivity cannot be cast to androidx.fragment.app.fragmentactivity..

pls help.

**Comment by dipinarora9** [comment]
Hey there!
Please make sure your app using andriodx libraries, then convert FlutterActivity to FlutterFragmentActivity in your MainActivity file under android/src/com/example.

I would recommend you go through the readme file of the plug-in thoroughly.
