### ISSUE TITLE
Issue with Java based flutter app.

### ISSUE THREAD

**Issue by hilo-red** [dipinarora9/flutter_truecaller#3]
Hello @dipinarora9 , thanks for the plugin. I have used the example you have provided, that works as promised.

However, I am trying to add the plugin to a java flavoured flutter app, it when I try "Get Profile" it throws "MainActivity cannot be cast to androidx.fragment.app.FragmentActivity".

I am unable to move forward. Is it related to the plugin? or I have to do something on my side?

**Comment by dipinarora9** [comment]
Hi @hilo-red , you are getting this error because you are trying to cast "Activity" to "FragmentActivity".
Truecaller SDK requires a Fragrament Activity for it to work.

Do the following and your error will be resolved.
https://pub.dev/packages/flutter_truecaller#3-for-truecaller-overlay

**Comment by hilo-red** [comment]
@dipinarora9 Thank you will follow that.

**Comment by hilo-red** [comment]
For those who are wondering how to do it. 

Your MainActivity.java must look like this.

`
package <yourpackage>;


import android.os.Bundle;
import io.flutter.embedding.android.FlutterFragmentActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;
import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;


public class MainActivity extends FlutterFragmentActivity {
  @Override
  public void configureFlutterEngine(@NonNull  FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
`

If the error still persists, follow this https://github.com/flutter/flutter/issues/50457

I had splashscreen and it failed with flutterfragment, I removed it but you can find fix here https://github.com/flutter/flutter/issues/47136
