### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by mouryaavadhesh** [dipinarora9/flutter_truecaller#5]
\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:23: error: cannot find symbol
    flutterEngine.getPlugins().add(new dipinarora9.flutter_truecaller.FlutterTruecallerPlugin());
                                                                     ^
  symbol:   class FlutterTruecallerPlugin
  location: package dipinarora9.flutter_truecaller
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by dipinarora9** [comment]
Hi @mouryaavadhesh ,
Could you please pass the output of `flutter doctor -v` command.
Also, is your app using flutter v2 embedding?

**Comment by mouryaavadhesh** [comment]
E:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)
    • Flutter version 1.19.0-4.1.pre at E:\flutter
    • Framework revision f994b76974 (7 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_SDK_ROOT = E:\sdk
    • Java binary at: E:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at E:\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\moury\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
Process finished with exit code 0

**Comment by mouryaavadhesh** [comment]
Everything is fine is a flutter doctore

**Comment by dipinarora9** [comment]
Is your app using flutter v2 embedding?
And flutter_truecaller plugin has Androidx dependencies, is your migrated to androidx?

**Comment by mouryaavadhesh** [comment]
Yes we have android x
and flutter v2 embedding
need to check how can I check that?

**Comment by mouryaavadhesh** [comment]
Also not using io.flutter.embedding.android.FlutterActivity

**Comment by dipinarora9** [comment]
You can check for v2 embedding in your AndroidManifest.xml and app/build.gradle for androidx dependencies.

Check for your MainActivity file does it registers the flutter engine as in [this](https://github.com/dipinarora9/flutter_truecaller/blob/master/example/android/app/src/main/kotlin/dipinarora9/flutter_truecaller_example/MainActivity.kt) file.

**Comment by dipinarora9** [comment]
@mouryaavadhesh okay so you are using io.flutter.embedding.android.FlutterFragmentActivity as specified.

**Comment by mouryaavadhesh** [comment]
yes 
and I have checked everything

**Comment by mouryaavadhesh** [comment]
using  io.flutter.embedding.android.FlutterFragmentActivity yes

**Comment by mouryaavadhesh** [comment]
@dipinarora9  update your dependency with the latest version like kotlin and true caller

**Comment by dipinarora9** [comment]
I have tried building the example app on the same flutter channel(1.19.0-4.1.pre) that you are using and the build was successful and all its functionality was working fine.

Also, you can try the updated package version of flutter_truecaller plugin.

If you are still facing the issue, download the source code for the example app and try building it on your system. Reply back with the output, so that I can understand what is causing the issue because I am unable to reproduce it.

**Comment by mouryaavadhesh** [comment]
I have already solved the issue by updated API's.
