### ISSUE TITLE
Truecaller login is not working  in release build 

### ISSUE THREAD

**Issue by vivekkujur** [dipinarora9/flutter_truecaller#6]
gradle build:
`
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.dvv.vd"
        minSdkVersion 16
        targetSdkVersion 29
        multiDexEnabled true  //ADD THIS LINE

        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
        }

    }`

 truecaller login is working fine on debug build. but not working on released build.

**Comment by dipinarora9** [comment]
use `flutter build apk --no-shrink`
or `flutter build appbundle --no-shrink`.
Flutter uses R8 shrinker by default, which causes problems with Truecaller SDK. Use `--no-shrink` flag to disable R8 shrinker.

**Comment by vivekkujur** [comment]
debug build is wok fine.
problem is in released build.
I did  `flutter build apk  --release --no-shrink`. but  same problem login not working .

**Comment by vivekkujur** [comment]
issue solved.
I was entered debug SHA-1 key on truecaller dev.
